name = "fermyon-developer"
spin_version = "1"
version = "0.1.0"
description = "The Fermyon Developer website running on... Spin."
authors = [ "Fermyon Engineering <engineering@fermyon.com>" ]
trigger = { type = "http", base = "/" }

[[component]]
source = "modules/bartholomew.wasm"
id = "bartholomew"
files = [ "content/**/*" , "templates/*", "scripts/*", "config/*", "shortcodes/*"]
[component.trigger]
route = "/..."

[[component]]
source = "modules/spin_static_fs.wasm"
id = "fileserver_static"
files = [ { source = "static/", destination = "/" } ]
[component.trigger]
route = "/static/..."

[[component]]
source = "modules/spin_static_fs.wasm"
id = "fileserver_downloads"
files = [ { source = "downloads/", destination = "/" } ]
[component.trigger]
route = "/downloads/..."

# Redirect /spin to /spin/index
[[component]]
id = "redirect-spin-index"
source = "modules/redirect.wasm"
environment = { DESTINATION = "/spin/index" }
[component.trigger]
route = "/spin"
executor = { type = "wagi" }

# Redirect /cloud to /cloud/index
[[component]]
id = "redirect-cloud-index"
source = "modules/redirect.wasm"
environment = { DESTINATION = "/cloud/index" }
[component.trigger]
route = "/cloud"
executor = { type = "wagi" }

# Redirect /bartholomew to /bartholomew/index
[[component]]
id = "redirect-bartholomew-index"
source = "modules/redirect.wasm"
environment = { DESTINATION = "/bartholomew/index" }
[component.trigger]
route = "/bartholomew"
executor = { type = "wagi" }

# Redirect /spin/contributing-docs to /common/contributing-docs
[[component]]
id = "redirect-contributing-spin-to-common"
source = "modules/redirect.wasm"
environment = { DESTINATION = "https://developer.fermyon.com/common/contributing-docs" }
[component.trigger]
route = "/spin/contributing-docs"
executor = { type = "wagi" }

# Redirect /cloud/contributing-docs to /common/contributing-docs
[[component]]
id = "redirect-contributing-cloud-to-common"
source = "modules/redirect.wasm"
environment = { DESTINATION = "https://developer.fermyon.com/common/contributing-docs" }
[component.trigger]
route = "/cloud/contributing-docs"
executor = { type = "wagi" }

# Redirect /bartholomew/contributing-docs to /common/contributing-docs
[[component]]
id = "redirect-contributing-bartholomew-to-common"
source = "modules/redirect.wasm"
environment = { DESTINATION = "https://developer.fermyon.com/common/contributing-docs" }
[component.trigger]
route = "/bartholomew/contributing-docs"
executor = { type = "wagi" }

# Redirect /spin/cli-reference to /common/cli-reference
[[component]]
id = "redirect-cli-reference-spin-to-common"
source = "modules/redirect.wasm"
environment = { DESTINATION = "https://developer.fermyon.com/common/cli-reference" }
[component.trigger]
route = "/spin/cli-reference"
executor = { type = "wagi" }

# Redirect /cloud/cli-reference to /common/cli-reference
[[component]]
id = "redirect-cli-reference-cloud-to-common"
source = "modules/redirect.wasm"
environment = { DESTINATION = "https://developer.fermyon.com/common/cli-reference" }
[component.trigger]
route = "/cloud/cli-reference"
executor = { type = "wagi" }

