name: Build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup Spin
        uses: fermyon/actions/spin/setup@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install bart
        run: |
          curl -LOs https://github.com/fermyon/bartholomew/releases/download/v0.8.0/bart
          chmod +x bart
          mv bart /usr/local/bin

      - name: Check Docs
        run: |
          bart check content/* && bart check content/**/*
      
      - name: Install npm packages
        run: |
          npm ci

      - name: Build app
        run: |
          spin build

      - name: Run npm tests
        run: |
          npm test
